### ISSUE TITLE
Error [For Windows] CrashHandlerException: Program crashed with signal 11

### ISSUE THREAD

**Issue by lavstudia** [GsLogiMaker/godot-glecs#23]
Run main.gs:

Input ready
Test start
  
  ================================================================
  CrashHandlerException: Program crashed with signal 11
  Engine version: Godot Engine v4.3.stable.mono.official (77dcf97d82cbfe4e4615475fa52ca03da645dbd8)
  Dumping the backtrace. Please include this when reporting the bug to the project developer.
  [1] error(-1): no debug info in PE/COFF executable
  [2] error(-1): no debug info in PE/COFF executable
  [3] error(-1): no debug info in PE/COFF executable
  [4] error(-1): no debug info in PE/COFF executable
  [5] error(-1): no debug info in PE/COFF executable
  [6] error(-1): no debug info in PE/COFF executable
  -- END OF BACKTRACE --
  ================================================================

**Comment by GsLogiMaker** [comment]
Which branch did you run? The most up to date, and functional branch is the cpp branch, which will be merged to the dev branch once it matches the dev branch in features. The main branch will not be functional until the first public release of Glecs.

**Comment by GsLogiMaker** [comment]
I also have not yet tested for operating systems other than Linux nor the mono build of Godot. This project is still fairly early, and I do not expect it to work on other machines yet.

**Comment by GsLogiMaker** [comment]
Thank you for your interest in the project!

**Comment by lavstudia** [comment]
Great project!

cpp branch. Minor modifications with SConstruct (addons/glecs/cpp) for successful assembly under Windows.

**Comment by GsLogiMaker** [comment]
What changes did you make? I might need to add them to the project.
Also, I don't think I setup the `.gdextension` file properly for any platforms other than linux x86_64 debug.

**Comment by lavstudia** [comment]
I’m not sure that I’m very competent in this matter, but for me this turned out to be a working option:

1.  ./addons/glecs/cpp/SConstruct 

```
...

platform:str = env["platform"]
target:str = env["target"]
suffix:str = env["suffix"]
shlib_suffix:str = env["SHLIBSUFFIX"]

# TODO: For Windows
env['CXXFLAGS'].remove('/std:c++17')
env.Append(CXXFLAGS=['/std:c++20'])

# For reference:
# - CCFLAGS are compilation flags shared between C and C++

# - CFLAGS are for C-specific compilation flags
# - CXXFLAGS are for C++-specific compilation flags
# - CPPFLAGS are for pre-processor flags
# - CPPDEFINES are for pre-processor defines
# - LINKFLAGS are for linking flags

...
```

2. ./addons/glecs/cpp/glecs.gdextension

```
...

windows.release.x86_64 = "./bin/libglecs.windows.template_debug.x86_64.dll"
windows.debug.x86_64 = "./bin/libglecs.windows.template_debug.x86_64.dll"

...
```

**Comment by GsLogiMaker** [comment]
That's weird that you need to change the cpp version to 20. When you build, you just run the command `scons` with no other arguments, right?

**Comment by GsLogiMaker** [comment]
It looks like a minor refactor to support C++17. I'll look into doing that.

**Comment by GsLogiMaker** [comment]
Is this fixed if you try the latest commit on the master branch?

**Comment by lavstudia** [comment]
I confirm! This fixes the error.
Thank you!
